# Generated by Django 5.2.12 on 2026-04-25 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cv_analyzer", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="auto_apply_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="cv_last_analyzed",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="cv_score",
            field=models.IntegerField(default=0, help_text="Latest CV score (0-100)"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="expected_salary_max",
            field=models.IntegerField(
                blank=True, help_text="Maximum expected salary", null=True
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="expected_salary_min",
            field=models.IntegerField(
                blank=True, help_text="Minimum expected salary", null=True
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="job_alerts_enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="last_job_search",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="latest_cv_analysis",
            field=models.OneToOneField(
                blank=True,
                help_text="Latest CV analysis for this user",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="user_profile",
                to="cv_analyzer.cvanalysis",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="preferred_locations",
            field=models.TextField(
                blank=True,
                help_text="Comma-separated preferred locations (e.g., Islamabad, Remote, Lahore)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="target_job_titles",
            field=models.TextField(
                blank=True,
                help_text="Comma-separated target job titles (e.g., Python Developer, Data Scientist)",
                null=True,
            ),
        ),
    ]
