"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.2.12.
Upgraded for CV Analyzer & Job Scraper (v2.1)
"""

from pathlib import Path
import os
import sys
import logging

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# ================================
# 🔐 SECURITY SETTINGS
# ================================
SECRET_KEY = "django-insecure-xd+eza)q%+zb+#3g16=p6l9wr0$2+an*1mmjr%myb6=c=0-7%%"
DEBUG = True
ALLOWED_HOSTS = ['*']  # ✅ CHANGED: Allow all for development


# ================================
# ✅ NEW: ANALYZER & SCRAPER PATHS
# ================================
# Add analyzer and scraper modules to Python path
sys.path.insert(0, os.path.join(BASE_DIR, 'analyzer'))
sys.path.insert(0, os.path.join(BASE_DIR, 'scraper'))

# Path to ML models (skill_db.json, market_skills.json)
ANALYZER_MODELS_PATH = os.path.join(BASE_DIR, 'models')


# Application definition
INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    # Your apps
    'users',
    'cv_analyzer',
    'jobs',
    'chatbot',
    'forum',
    'dashboard',
    'resource_hub',      
    'notifications',     
    'ai_interview', 
]


MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]


ROOT_URLCONF = "core.urls"


TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR, 'templates')],  # ✅ CHANGED: Use os.path.join
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                # ✅ NEW: Add media context processor for file uploads
                "django.template.context_processors.media",
            ],
        },
    },
]


WSGI_APPLICATION = "core.wsgi.application"


# Database
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# ================================
# 🔐 AUTHENTICATION SETTINGS
# ================================
AUTH_USER_MODEL = 'auth.User'
LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'home'
LOGOUT_REDIRECT_URL = 'login'


# ================================
# 🔑 PASSWORD VALIDATION
# ================================
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {
            'min_length': 8,
        }
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# ================================
# 🕒 SESSION SETTINGS
# ================================
SESSION_COOKIE_AGE = 1209600  # 2 weeks
SESSION_EXPIRE_AT_BROWSER_CLOSE = False


# ================================
# 🌍 INTERNATIONALIZATION
# ================================
LANGUAGE_CODE = "en-us"
TIME_ZONE = "UTC"
USE_I18N = True
USE_TZ = True


# ================================
# 📁 STATIC FILES
# ================================
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')  # ✅ NEW
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]


# ================================
# 📂 MEDIA FILES
# ================================
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


# ================================
# 📤 FILE UPLOAD SETTINGS
# ================================
DATA_UPLOAD_MAX_MEMORY_SIZE = 5242880  # 5MB
FILE_UPLOAD_MAX_MEMORY_SIZE = 5242880  # 5MB
FILE_UPLOAD_TEMP_DIR = os.path.join(BASE_DIR, 'temp')  # ✅ NEW: Temp directory for uploads


# ================================
# 🔑 DEFAULT PRIMARY KEY
# ================================
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# ================================
# 🎯 CV ANALYZER SETTINGS
# ================================
CV_ANALYSIS_MAX_FILE_SIZE = 5 * 1024 * 1024  # 5MB
ALLOWED_CV_FORMATS = ['pdf', 'doc', 'docx']

# ✅ NEW: Logging configuration for analyzer/scraper modules
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
            'level': 'INFO',
        },
        'file': {
            'class': 'logging.FileHandler',
            'filename': os.path.join(BASE_DIR, 'logs', 'django.log'),
            'formatter': 'verbose',
            'level': 'INFO',
        },
    },
    'root': {
        'handlers': ['console', 'file'],
        'level': 'INFO',
    },
    'loggers': {
        'analyzer': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
        'scraper': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
        'django': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}

# Ensure logs directory exists
LOGS_DIR = os.path.join(BASE_DIR, 'logs')
if not os.path.exists(LOGS_DIR):
    os.makedirs(LOGS_DIR, exist_ok=True)

# Ensure temp directory exists
TEMP_DIR = os.path.join(BASE_DIR, 'temp')
if not os.path.exists(TEMP_DIR):
    os.makedirs(TEMP_DIR, exist_ok=True)


# ================================
# ⚙️ CELERY (OPTIONAL - for auto-apply)
# ================================
try:
    CELERY_BROKER_URL = 'redis://localhost:6379'
    CELERY_RESULT_BACKEND = 'redis://localhost:6379'
    CELERY_ACCEPT_CONTENT = ['json']
    CELERY_TASK_SERIALIZER = 'json'
    CELERY_RESULT_SERIALIZER = 'json'
    CELERY_TIMEZONE = 'UTC'
    
    from celery.schedules import crontab
    
    CELERY_BEAT_SCHEDULE = {
        'auto-apply': {
            'task': 'jobs.tasks.scheduled_auto_apply',
            'schedule': crontab(minute=0, hour='*/2'),  # Every 2 hours
        },
    }
except ImportError:
    pass


# ================================
# ✅ NEW: ML/AI MODEL SETTINGS
# ================================
# Disable transformers warning if not using GPU
os.environ['TOKENIZERS_PARALLELISM'] = 'false'

# spaCy model name
SPACY_MODEL = 'en_core_web_sm'

# Sentence transformers model
SIMILARITY_MODEL = 'sentence-transformers/all-MiniLM-L6-v2'

# Cache timeout for job scraper (6 hours)
SCRAPER_CACHE_TTL = 6 * 60 * 60

# Max jobs per scraper
MAX_JOBS_PER_PORTAL = 20