# Generated by Django 4.2.11 on 2026-04-28 22:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="notification",
            name="notificatio_user_id_05b4bc_idx",
        ),
        migrations.RemoveIndex(
            model_name="notification",
            name="notificatio_is_read_9edb86_idx",
        ),
        migrations.AddField(
            model_name="notification",
            name="dedupe_key",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="notification",
            name="metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["user", "is_archived", "-created_at"],
                name="notificatio_user_id_f31d89_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["user", "is_archived", "is_read"],
                name="notificatio_user_id_ed8c72_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["user", "dedupe_key"], name="notificatio_user_id_4f70d5_idx"
            ),
        ),
    ]
